name: release

on:
  push:
    tags:
      - "*"

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Version
        uses: rexdefuror/read-package-json@v1.0.5

      - name: Check docker version
        run: docker -v

      - name: Build the Docker image
        run: docker build -t hopgoldy/cube-probe:${{ env.PACKAGE_VERSION }} .

      - name: Log in to Docker Hub
        run: docker login -u hopgoldy -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push hopgoldy/cube-probe:${{ env.PACKAGE_VERSION }}
